# Pistachio Classification

**Selected Machine Learning Exercise**

Binary classification of pistachio varieties using geometric and shape features.

In [440]:
import pandas as pd
import numpy as np

In [ ]:
pistachio = pd.read_csv("data/train.csv")

In [442]:
pistachio.shape

(1718, 17)

In [443]:
pistachio.head()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,ROUNDNESS,COMPACTNESS,SHAPEFACTOR_1,SHAPEFACTOR_2,SHAPEFACTOR_3,SHAPEFACTOR_4,Class
0,73107,1161.8070,442.4074,217.7261,0.8705,305.0946,0.9424,77579,0.7710,2.0319,0.6806,0.6896,0.0061,0.0030,0.4756,0.9664,Kirmizi_Pistachio
1,89272,1173.1810,460.2551,251.9546,0.8369,337.1419,0.9641,92598,0.7584,1.8267,0.8151,0.7325,0.0052,0.0028,0.5366,0.9802,Siit_Pistachio
2,60955,999.7890,386.9247,209.1255,0.8414,278.5863,0.9465,64400,0.7263,1.8502,0.7663,0.7200,0.0063,0.0034,0.5184,0.9591,Kirmizi_Pistachio
3,79537,1439.5129,466.7973,221.2136,0.8806,318.2289,0.9437,84281,0.7568,2.1102,0.4823,0.6817,0.0059,0.0028,0.4648,0.9807,Kirmizi_Pistachio
4,96395,1352.6740,515.8730,246.5945,0.8784,350.3340,0.9549,100950,0.7428,2.0920,0.6620,0.6791,0.0054,0.0026,0.4612,0.9648,Kirmizi_Pistachio

In [444]:
pistachio.info()

<class 'pandas.DataFrame'>
RangeIndex: 1718 entries, 0 to 1717
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   AREA           1718 non-null   int64
 1   PERIMETER      1718 non-null   float64
 2   MAJOR_AXIS     1718 non-null   float64
 3   MINOR_AXIS     1718 non-null   float64
 4   ECCENTRICITY   1718 non-null   float64
 5   EQDIASQ        1718 non-null   float64
 6   SOLIDITY       1718 non-null   float64
 7   CONVEX_AREA    1718 non-null   int64
 8   EXTENT         1718 non-null   float64
 9   ASPECT_RATIO   1718 non-null   float64
 10  ROUNDNESS      1718 non-null   float64
 11  COMPACTNESS    1718 non-null   float64
 12  SHAPEFACTOR_1  1718 non-null   float64
 13  SHAPEFACTOR_2  1718 non-null   float64
 14  SHAPEFACTOR_3  1718 non-null   float64
 15  SHAPEFACTOR_4  1718 non-null   float64
 16  Class          1718 non-null   str
dtypes: float64(14), int64(2), str(1)
memory usage: 228.3 KB

In [445]:
pistachio.describe()

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,ROUNDNESS,COMPACTNESS,SHAPEFACTOR_1,SHAPEFACTOR_2,SHAPEFACTOR_3,SHAPEFACTOR_4
count,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000,1718.000000
mean,79871.952852,1421.797588,446.206444,238.193128,0.840347,317.790000,0.940103,84947.671129,0.716055,1.899342,0.570831,0.712841,0.005704,0.003017,0.510097,0.955185
std,12968.217051,373.408835,31.885328,30.426445,0.049026,26.571699,0.050006,13081.742551,0.052534,0.241253,0.211514,0.044230,0.000810,0.000334,0.063391,0.051735
min,29808.000000,858.363000,321.425500,133.509600,0.504900,194.814600,0.588000,37935.000000,0.427200,1.158500,0.062800,0.476000,0.004000,0.002400,0.226600,0.620400
25%,71898.500000,1169.633225,426.554100,217.875475,0.817500,302.562375,0.920250,76357.750000,0.688100,1.736325,0.372325,0.682000,0.005200,0.002800,0.465125,0.944200
50%,79795.000000,1260.785500,448.453150,235.888750,0.850250,318.744650,0.953800,84973.000000,0.726100,1.899550,0.643850,0.709750,0.005600,0.003000,0.503750,0.972800
75%,88980.000000,1599.479000,467.515200,257.433625,0.875375,336.590000,0.976300,93660.750000,0.753600,2.068575,0.744450,0.741600,0.006100,0.003200,0.549975,0.986800
max,124008.000000,2755.049100,535.642200,383.046100,0.946000,397.356100,0.995100,132478.000000,0.820400,3.085800,0.933600,0.869500,0.013100,0.005300,0.756100,0.999000

In [446]:
df_corr = pistachio.copy()

df_corr["Class_encoded"] = df_corr["Class"].map({
    "Kirmizi_Pistachio": 0,
    "Siit_Pistachio": 1
})

corr_table = df_corr.corr(numeric_only=True).round(2).abs()

corr_table

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,ROUNDNESS,COMPACTNESS,SHAPEFACTOR_1,SHAPEFACTOR_2,SHAPEFACTOR_3,SHAPEFACTOR_4,Class_encoded
AREA,1.00,0.13,0.69,0.79,0.36,1.00,0.35,0.94,0.33,0.44,0.24,0.56,0.89,0.64,0.55,0.28,0.60
PERIMETER,0.13,1.00,0.10,0.40,0.35,0.12,0.67,0.37,0.40,0.32,0.89,0.06,0.09,0.28,0.06,0.63,0.15
MAJOR_AXIS,0.69,0.10,1.00,0.27,0.29,0.70,0.24,0.65,0.18,0.26,0.15,0.20,0.38,0.79,0.21,0.19,0.15
MINOR_AXIS,0.79,0.40,0.27,1.00,0.82,0.79,0.11,0.89,0.04,0.85,0.07,0.77,0.85,0.06,0.77,0.21,0.67
ECCENTRICITY,0.36,0.35,0.29,0.82,1.00,0.36,0.28,0.50,0.09,0.94,0.18,0.84,0.58,0.42,0.85,0.36,0.54
EQDIASQ,1.00,0.12,0.70,0.79,0.36,1.00,0.35,0.94,0.33,0.44,0.25,0.56,0.91,0.65,0.55,0.28,0.58
SOLIDITY,0.35,0.67,0.24,0.11,0.28,0.35,1.00,0.02,0.67,0.19,0.77,0.21,0.36,0.73,0.20,0.95,0.12
CONVEX_AREA,0.94,0.37,0.65,0.89,0.50,0.94,0.02,1.00,0.12,0.54,0.02,0.52,0.83,0.42,0.52,0.04,0.59
EXTENT,0.33,0.40,0.18,0.04,0.09,0.33,0.67,0.12,1.00,0.02,0.52,0.25,0.36,0.51,0.24,0.64,0.10
ASPECT_RATIO,0.44,0.32,0.26,0.85,0.94,0.44,0.19,0.54,0.02,1.00,0.11,0.90,0.69,0.32,0.89,0.27,0.57
ROUNDNESS,0.24,0.89,0.15,0.07,0.18,0.25,0.77,0.02,0.52,0.11,1.00,0.17,0.25,0.48,0.16,0.68,0.10
COMPACTNESS,0.56,0.06,0.20,0.77,0.84,0.56,0.21,0.52,0.25,0.90,0.17,1.00,0.81,0.03,1.00,0.16,0.62
SHAPEFACTOR_1,0.89,0.09,0.38,0.85,0.58,0.91,0.36,0.83,0.36,0.69,0.25,0.81,1.00,0.44,0.79,0.28,0.62
SHAPEFACTOR_2,0.64,0.28,0.79,0.06,0.42,0.65,0.73,0.42,0.51,0.32,0.48,0.03,0.44,1.00,0.04,0.73,0.13
SHAPEFACTOR_3,0.55,0.06,0.21,0.77,0.85,0.55,0.20,0.52,0.24,0.89,0.16,1.00,0.79,0.04,1.00,0.16,0.62
SHAPEFACTOR_4,0.28,0.63,0.19,0.21,0.36,0.28,0.95,0.04,0.64,0.27,0.68,0.16,0.28,0.73,0.16,1.00,0.05
Class_encoded,0.60,0.15,0.15,0.67,0.54,0.58,0.12,0.59,0.10,0.57,0.10,0.62,0.62,0.13,0.62,0.05,1.00

In [447]:
corr_table["Class_encoded"].sort_values(ascending=False)

Class_encoded    1.00
MINOR_AXIS       0.67
COMPACTNESS      0.62
SHAPEFACTOR_1    0.62
SHAPEFACTOR_3    0.62
AREA             0.60
CONVEX_AREA      0.59
EQDIASQ          0.58
ASPECT_RATIO     0.57
ECCENTRICITY     0.54
PERIMETER        0.15
MAJOR_AXIS       0.15
SHAPEFACTOR_2    0.13
SOLIDITY         0.12
EXTENT           0.10
ROUNDNESS        0.10
SHAPEFACTOR_4    0.05
Name: Class_encoded, dtype: float64

In [448]:
high_corr = corr_table.where(np.triu(np.ones(corr_table.shape), k=1).astype(bool)).stack().reset_index()

high_corr.columns = ["feature_1", "feature_2", "correlation"]

high_corr = high_corr[high_corr["correlation"] > 0.8].sort_values("correlation", ascending=False)

high_corr

        feature_1      feature_2  correlation
5            AREA        EQDIASQ         1.00
201   COMPACTNESS  SHAPEFACTOR_3         1.00
117      SOLIDITY  SHAPEFACTOR_4         0.95
77   ECCENTRICITY   ASPECT_RATIO         0.94
7            AREA    CONVEX_AREA         0.94
92        EQDIASQ    CONVEX_AREA         0.94
97        EQDIASQ  SHAPEFACTOR_1         0.91
164  ASPECT_RATIO    COMPACTNESS         0.90
12           AREA  SHAPEFACTOR_1         0.89
58     MINOR_AXIS    CONVEX_AREA         0.89
27      PERIMETER      ROUNDNESS         0.89
167  ASPECT_RATIO  SHAPEFACTOR_3         0.89
60     MINOR_AXIS   ASPECT_RATIO         0.85
63     MINOR_AXIS  SHAPEFACTOR_1         0.85
82   ECCENTRICITY  SHAPEFACTOR_3         0.85
79   ECCENTRICITY    COMPACTNESS         0.84
131   CONVEX_AREA  SHAPEFACTOR_1         0.83
55     MINOR_AXIS   ECCENTRICITY         0.82
199   COMPACTNESS  SHAPEFACTOR_1         0.81

In [449]:
pistachio.duplicated().sum()

np.int64(0)

In [450]:
pistachio["Class"].value_counts()

Class
Kirmizi_Pistachio    998
Siit_Pistachio       720
Name: count, dtype: int64

In [451]:
x = pistachio.drop(columns=["Class"])
y = pistachio["Class"]

In [452]:
from sklearn.model_selection import train_test_split

x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42, stratify=y)

## baseline model

(knn is sensetive to the distances. we'll do scaling)

In [453]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import f1_score

baseline_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier())
])

baseline_pipeline.fit(x_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()), ('knn', KNeighborsClassifier())])

In [454]:
y_pred = baseline_pipeline.predict(x_val)

score = f1_score(y_val, y_pred, average="weighted")

print("fscore:", score)

fscore: 0.8453361383924985

## feature engineering

In [455]:
cols_to_drop = [
    "EQDIASQ",
    "CONVEX_AREA",
    "SHAPEFACTOR_3",
    "SHAPEFACTOR_4",
    "ASPECT_RATIO"
]

x_train_reduced = x_train.drop(columns=cols_to_drop)
x_val_reduced = x_val.drop(columns=cols_to_drop)

In [456]:
baseline_pipeline.fit(x_train_reduced, y_train)

y_pred = baseline_pipeline.predict(x_val_reduced)

score = f1_score(y_val, y_pred, average="weighted")

print("Weighted F1-score after removing corr cols:", score)

Weighted F1-score after removing corr cols: 0.8596571409916877

prioritize feature selection over creating lots of new features. KNN suffers from the curse of dimensionality, so extra noisy features can make distances less meaningful.

In [457]:
from sklearn.feature_selection import mutual_info_classif
import pandas as pd

mi = mutual_info_classif(x_train_reduced, y_train, random_state=42)

mi_scores = pd.Series(mi, index=x_train_reduced.columns).sort_values(ascending=False)

mi_scores

SHAPEFACTOR_1    0.325504
MINOR_AXIS       0.322371
COMPACTNESS      0.250240
AREA             0.242348
ECCENTRICITY     0.213748
SOLIDITY         0.060944
ROUNDNESS        0.055770
PERIMETER        0.037917
MAJOR_AXIS       0.026432
EXTENT           0.006480
SHAPEFACTOR_2    0.000000
dtype: float64

In [458]:
for n in [5, 8, 10, 12, 15]:
    
    top_features = mi_scores.head(n).index

    baseline_pipeline.fit(x_train_reduced[top_features], y_train)

    y_pred = baseline_pipeline.predict(x_val_reduced[top_features])

    score = f1_score(y_val, y_pred, average="weighted")

    print(f"Top {n} features: {score:.4f}")

Top 5 features: 0.8480
Top 8 features: 0.8478
Top 10 features: 0.8542
Top 12 features: 0.8597
Top 15 features: 0.8597

In [459]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.feature_selection import SelectKBest, mutual_info_classif

cv_pipeline = Pipeline([
    ("selector", SelectKBest(
        score_func=mutual_info_classif,
        k=11
    )),
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier())
])

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

scores = cross_val_score(
    cv_pipeline,
    x_train_reduced,
    y_train,
    cv=cv,
    scoring="f1_weighted"
)

print("Scores:", scores)
print("Mean F1:", scores.mean())
print("Std:", scores.std())

Scores: [0.87209197 0.84390311 0.865937   0.87960721 0.82193066]
Mean F1: 0.8566939885635876
Std: 0.021069608291884315

In [460]:
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

for k in range(5, 12):

    pipeline = Pipeline([
        ("selector", SelectKBest(
            score_func=mutual_info_classif,
            k=k
        )),
        ("scaler", StandardScaler()),
        ("knn", KNeighborsClassifier())])

    scores = cross_val_score(pipeline, x_train_reduced, y_train, cv=cv, scoring="f1_weighted")

    print(
        f"Top {k}: "
        f"mean={scores.mean():.4f}, "
          f"std={scores.std():.4f}")

Top 5: mean=0.8483, std=0.0199
Top 6: mean=0.8468, std=0.0180
Top 7: mean=0.8442, std=0.0268
Top 8: mean=0.8478, std=0.0176
Top 9: mean=0.8543, std=0.0146
Top 10: mean=0.8567, std=0.0180
Top 11: mean=0.8567, std=0.0211

In [461]:
# import numpy as np

# def add_log_features(df):
#     df = df.copy()

#     df["LOG_AREA"] = np.log1p(df["AREA"])
#     df["LOG_PERIMETER"] = np.log1p(df["PERIMETER"])
#     df["LOG_MAJOR_AXIS"] = np.log1p(df["MAJOR_AXIS"])
#     df["LOG_MINOR_AXIS"] = np.log1p(df["MINOR_AXIS"])

#     return df

In [462]:
# x_train_log = add_log_features(x_train_reduced)

# pipeline = Pipeline([
#     ("scaler", StandardScaler()),
#     ("knn", KNeighborsClassifier())
# ])

# scores = cross_val_score(
#     pipeline,
#     x_train_log,
#     y_train,
#     cv=cv,
#     scoring="f1_weighted"
# )

# print("Log features")
# print("Mean:", scores.mean())
# print("Std:", scores.std())

In [463]:
# def add_shape_interactions(df):
#     df = df.copy()

#     df["ROUNDNESS_SOLIDITY"] = (
#         df["ROUNDNESS"] * df["SOLIDITY"])

#     df["ECCENTRICITY_ROUNDNESS"] = (
#         df["ECCENTRICITY"] * df["ROUNDNESS"])

#     df["COMPACTNESS_SOLIDITY"] = (
#         df["COMPACTNESS"] * df["SOLIDITY"])

#     df["EXTENT_SOLIDITY"] = (
#         df["EXTENT"] * df["SOLIDITY"])

#     return df

In [464]:
# x_train_shape = add_shape_interactions(x_train_reduced)

# scores = cross_val_score(pipeline, x_train_shape, y_train, cv=cv, scoring="f1_weighted")

# print("Shape interactions")
# print("Mean:", scores.mean())
# print("Std:", scores.std())

In [465]:
interaction_features = {
    "ROUNDNESS_SOLIDITY":
        x_train_reduced["ROUNDNESS"] * x_train_reduced["SOLIDITY"],

    "ECCENTRICITY_ROUNDNESS":
        x_train_reduced["ECCENTRICITY"] * x_train_reduced["ROUNDNESS"],

    "COMPACTNESS_SOLIDITY":
        x_train_reduced["COMPACTNESS"] * x_train_reduced["SOLIDITY"],

    "EXTENT_SOLIDITY":
        x_train_reduced["EXTENT"] * x_train_reduced["SOLIDITY"]
}

for name, feature in interaction_features.items():

    x_temp = x_train_reduced.copy()
    x_temp[name] = feature

    scores = cross_val_score(
        pipeline,
        x_temp,
        y_train,
        cv=cv,
        scoring="f1_weighted"
    )

    print(
        f"{name}: "
        f"mean={scores.mean():.4f}, "
        f"std={scores.std():.4f}"
    )

ROUNDNESS_SOLIDITY: mean=0.8564, std=0.0205
ECCENTRICITY_ROUNDNESS: mean=0.8567, std=0.0166
COMPACTNESS_SOLIDITY: mean=0.8637, std=0.0218
EXTENT_SOLIDITY: mean=0.8560, std=0.0178

In [466]:
from itertools import combinations

def add_selected_interactions(df, selected):
    df = df.copy()

    if "ROUNDNESS_SOLIDITY" in selected:
        df["ROUNDNESS_SOLIDITY"] = (
            df["ROUNDNESS"] * df["SOLIDITY"]
        )

    if "ECCENTRICITY_ROUNDNESS" in selected:
        df["ECCENTRICITY_ROUNDNESS"] = (
            df["ECCENTRICITY"] * df["ROUNDNESS"]
        )

    if "COMPACTNESS_SOLIDITY" in selected:
        df["COMPACTNESS_SOLIDITY"] = (
            df["COMPACTNESS"] * df["SOLIDITY"]
        )

    if "EXTENT_SOLIDITY" in selected:
        df["EXTENT_SOLIDITY"] = (
            df["EXTENT"] * df["SOLIDITY"]
        )

    return df


features = [
    "ROUNDNESS_SOLIDITY",
    "ECCENTRICITY_ROUNDNESS",
    "COMPACTNESS_SOLIDITY",
    "EXTENT_SOLIDITY"
]

results = []

for r in range(1, len(features) + 1):

    for combo in combinations(features, r):

        x_temp = add_selected_interactions(
            x_train_reduced,
            combo
        )

        scores = cross_val_score(
            pipeline,
            x_temp,
            y_train,
            cv=cv,
            scoring="f1_weighted"
        )

        results.append({
            "features": combo,
            "mean_f1": scores.mean(),
            "std": scores.std()
        })

In [467]:
import pandas as pd

results_df = pd.DataFrame(results)

results_df.sort_values(
    "mean_f1",
    ascending=False
).head(10)

                                             features   mean_f1       std
2                             (COMPACTNESS_SOLIDITY,)  0.861578  0.025070
5          (ROUNDNESS_SOLIDITY, COMPACTNESS_SOLIDITY)  0.859295  0.013864
0                               (ROUNDNESS_SOLIDITY,)  0.858599  0.020695
8           (ECCENTRICITY_ROUNDNESS, EXTENT_SOLIDITY)  0.858474  0.015932
3                                  (EXTENT_SOLIDITY,)  0.858202  0.019448
9             (COMPACTNESS_SOLIDITY, EXTENT_SOLIDITY)  0.857416  0.015987
1                           (ECCENTRICITY_ROUNDNESS,)  0.857231  0.016749
12  (ROUNDNESS_SOLIDITY, COMPACTNESS_SOLIDITY, EXT...  0.855550  0.025138
6               (ROUNDNESS_SOLIDITY, EXTENT_SOLIDITY)  0.855218  0.019271
4        (ROUNDNESS_SOLIDITY, ECCENTRICITY_ROUNDNESS)  0.854143  0.015357

In [468]:
from sklearn.model_selection import RepeatedStratifiedKFold, cross_val_score
import pandas as pd

repeated_cv = RepeatedStratifiedKFold(
    n_splits=5,
    n_repeats=10,
    random_state=42
)

candidates = {
    "baseline": (),
    
    "compactness_extent": (
        "COMPACTNESS_SOLIDITY",
        "EXTENT_SOLIDITY"
    ),

    "roundness_compactness_extent": (
        "ROUNDNESS_SOLIDITY",
        "COMPACTNESS_SOLIDITY",
        "EXTENT_SOLIDITY"
    ),

    "all_four": (
        "ROUNDNESS_SOLIDITY",
        "ECCENTRICITY_ROUNDNESS",
        "COMPACTNESS_SOLIDITY",
        "EXTENT_SOLIDITY"
    )
}

results = []

for name, combo in candidates.items():

    x_temp = add_selected_interactions(
        x_train_reduced,
        combo
    )

    scores = cross_val_score(
        pipeline,
        x_temp,
        y_train,
        cv=repeated_cv,
        scoring="f1_weighted"
    )

    results.append({
        "model": name,
        "mean_f1": scores.mean(),
        "std": scores.std(),
        "min_f1": scores.min(),
        "max_f1": scores.max()
    })

pd.DataFrame(results).sort_values(
    "mean_f1",
    ascending=False
)

                          model   mean_f1       std    min_f1    max_f1
1            compactness_extent  0.856305  0.017983  0.818585  0.898301
2  roundness_compactness_extent  0.856231  0.016040  0.814362  0.882729
0                      baseline  0.855892  0.016530  0.818394  0.886519
3                      all_four  0.855541  0.015817  0.821925  0.893956

In [469]:
# def add_best_interactions(df):
#     df = df.copy()

#     df["ROUNDNESS_SOLIDITY"] = (
#         df["ROUNDNESS"] * df["SOLIDITY"]
#     )

#     df["COMPACTNESS_SOLIDITY"] = (
#         df["COMPACTNESS"] * df["SOLIDITY"]
#     )

#     df["EXTENT_SOLIDITY"] = (
#         df["EXTENT"] * df["SOLIDITY"]
#     )

#     return df


# x_train_fe = add_best_interactions(x_train_reduced)
# x_val_fe = add_best_interactions(x_val_reduced)

In [470]:
# x_train_shape = add_best_interactions(x_train_reduced)

# scores = cross_val_score(pipeline, x_train_shape, y_train, cv=cv, scoring="f1_weighted")

# print("Shape interactions")
# print("Mean:", scores.mean())
# print("Std:", scores.std())

In [471]:
# def add_size_shape_features(df):
#     df = df.copy()

#     df["AREA_COMPACTNESS"] = (
#         df["AREA"] * df["COMPACTNESS"]
#     )

#     df["AREA_SOLIDITY"] = (
#         df["AREA"] * df["SOLIDITY"]
#     )

#     df["PERIMETER_ROUNDNESS"] = (
#         df["PERIMETER"] * df["ROUNDNESS"]
#     )

#     return df

In [472]:
# x_train_size_shape = add_size_shape_features(
#     x_train_reduced
# )

# scores = cross_val_score(
#     pipeline,
#     x_train_size_shape,
#     y_train,
#     cv=repeated_cv,
#     scoring="f1_weighted"
# )

# print("Size-shape features")
# print("Mean F1:", scores.mean())
# print("Std:", scores.std())

In [473]:
import numpy as np

def log_transform_features(df):
    df = df.copy()

    cols = [
        "AREA",
        "PERIMETER",
        "MAJOR_AXIS",
        "MINOR_AXIS"
    ]

    for col in cols:
        if col in df.columns:
            df[col] = np.log1p(df[col])

    return df

In [474]:
x_train_log = log_transform_features(x_train_reduced)

scores = cross_val_score(
    pipeline,
    x_train_log,
    y_train,
    cv=repeated_cv,
    scoring="f1_weighted"
)

print("Log-transformed features")
print("Mean F1:", scores.mean())
print("Std:", scores.std())

Log-transformed features
Mean F1: 0.8558729681038989
Std: 0.015729370499376876

In [475]:
log_cols = [
    "AREA",
    "PERIMETER",
    "MAJOR_AXIS",
    "MINOR_AXIS"
]

for col in log_cols:
    if col not in x_train_reduced.columns:
        continue

    x_temp = x_train_reduced.copy()
    x_temp[col] = np.log1p(x_temp[col])

    scores = cross_val_score(
        pipeline,
        x_temp,
        y_train,
        cv=repeated_cv,
        scoring="f1_weighted"
    )

    print(
        f"{col}: "
        f"mean={scores.mean():.4f}, "
        f"std={scores.std():.4f}"
    )

AREA: mean=0.8562, std=0.0164
PERIMETER: mean=0.8548, std=0.0153
MAJOR_AXIS: mean=0.8566, std=0.0171
MINOR_AXIS: mean=0.8559, std=0.0171

In [ ]:
test_data = pd.read_csv("data/test.csv")
test_data

In [477]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = pistachio.drop(columns=["Class"])
y = pistachio["Class"]

cols_to_drop = [
    "EQDIASQ",
    "CONVEX_AREA",
    "SHAPEFACTOR_3",
    "SHAPEFACTOR_4",
    "ASPECT_RATIO"
]

X = X.drop(columns=cols_to_drop)

x_train, x_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_val_scaled = scaler.transform(x_val)

In [478]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

model.fit(x_train_scaled, y_train)

KNeighborsClassifier()

In [479]:
from sklearn.metrics import f1_score

val_pred = model.predict(x_val_scaled)

score = f1_score(
    y_val,
    val_pred,
    average="weighted"
)

print("Weighted F1-score:", score)

Weighted F1-score: 0.8596571409916877

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

X_full = pistachio.drop(columns=["Class"])
y_full = pistachio["Class"]

X_full = X_full.drop(columns=cols_to_drop)
X_test = test_data.drop(columns=cols_to_drop)

final_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier()),
])

final_pipeline.fit(X_full, y_full)

In [ ]:
from pathlib import Path
Path("outputs").mkdir(exist_ok=True)

# predict test samples
test_pred = final_pipeline.predict(X_test)

prediction = pd.DataFrame({
    "Class": test_pred
})

prediction.to_csv("outputs/submission.csv", index=False)

print(prediction.shape)
prediction.head()

In [482]:
print(prediction.shape)
print(prediction["Class"].value_counts())
print(prediction.head())

(430, 1)
Class
Kirmizi_Pistachio    235
Siit_Pistachio       195
Name: count, dtype: int64
               Class
0     Siit_Pistachio
1     Siit_Pistachio
2     Siit_Pistachio
3     Siit_Pistachio
4  Kirmizi_Pistachio

In [ ]:
import joblib
import zipfile

joblib.dump(final_pipeline, "outputs/pistachio_pipeline.joblib")

artifact_files = [
    "outputs/submission.csv",
    "outputs/pistachio_pipeline.joblib",
]

with zipfile.ZipFile("outputs/model_artifacts.zip", mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
    for file_name in artifact_files:
        zf.write(file_name, arcname=Path(file_name).name)

print("Created outputs/model_artifacts.zip")